apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgclassification
spec:
  replicas: 3
  selector:
    matchLabels:
      app: imgclassification
  template:
    metadata:
      labels:
        app: imgclassification
    spec:
      containers:
      - name: ic-container
        image: us-west3-docker.pkg.dev/paa63-414501/cloud-run-source-deploy/cmpt-756-imageclassification/cmpt-756-imageclassification:4943f49b8398395d530b35d09bfdc2066df686f9
        ports:
        - containerPort: 5000
